### ISSUE TITLE
Twitter Cards

### ISSUE THREAD

**Issue by javieret** [grillorafael/bigseo#1]
Great library, you can add support to twitter cards library adding 
        "Twitterbot/1.0": true to the list of UA

Thank you.

**Comment by grillorafael** [comment]
Hi @javieret!

Thanks for the suggestion. I'll add this UA during the weekend!

**Comment by grillorafael** [comment]
Hi @javieret. Sorry for taking so long. You can now update to version d39bb39169a17ec8c519174bd16a23d8ef4ebae1 (0.6.4)
